### PR TITLE
Html+css

### PR DESCRIPTION
**Pull request by Keckich**
Одностраничный сайт, делал согласно своим макетам, но, очевидно, некоторые изменения/дополнения присутствуют. Все ссылки/кнопки уже в рабочем состоянии. Сайт: https://teadb-34ad1.firebaseapp.com/. Описанный функционал для данной темы реализовал следующим образом: 

- На странице "Collections" отображается то, что добавляет на сайт администрация (в моем лице), а на странице "User's tea" - то, что добавили зарегистрированные пользователи. 

- Страницы входа и регистрации я объединил в одну, а переход между соответствующими формами - по вкладкам. 

- Поиск осуществляется по наименованию коллекции (категории) и названию чая, вписанного в нужное поле (не менее 3-ех символов).

### CODE REVIEW

**Review by gmltA — COMMENTED** [review]
It's a <kbd>6</kbd> for now. To improve it, make sure all interactive elements have `:focus` styles.

**Comment by Keckich** [comment]
Added :focus state on all interactive elements(links, inputs, buttons, select, textarea). Not sure about focus state on logo in the header(is it really necessary?), but i did what you asked for. Also I tried to experiment with :focus-within state on review form. Is there anything else what I should do to improve my site?

**Review by gmltA — CHANGES_REQUESTED** [review]
A focus style would normally help user to quickly understand which page part are you on. Can you fulfill that?

**Review by gmltA — CHANGES_REQUESTED** [review]
Did you notice layout shift when you add a border to the element? That's not a good thing. For users with perception problems it may have some undesired consequences. You can use `box-shadow` to achieve the same effect but without layout shift. And you can also animate box shadow to make this effect even more sleek. Can you do that?

**Comment by Keckich** [comment]
Thanks for the advice about box-shadow, it really looks and seems better in this way. Also I tried to animate it with transition property.

**Review by gmltA — COMMENTED** [review]
Good. That's <kbd>8</kbd>. Is that enough?

**Comment by Keckich** [comment]
Is there anything what can be done to get 9?

**Comment by gmltA** [comment]
Obtain dark / light theme preferences from the browser, but leave the user ability to change it.

**Comment by Keckich** [comment]
I did it by using 'prefers-color-scheme:'. Now it will use user prefernces to know what theme should be display, but if user will change it by using switchbar on the site it will store in local storage. So by using switchbar variable 'theme' in local storage will be 'dark' or 'light', if user changes his prefernces it will be 'user-pref'. I used only js to did it. As I understand you don't want to see any js in this pr, so maybe you can check code via  page code (js/theme.js) or just change user preferences on your machine?

**Comment by Keckich** [comment]
(I added some functionality, so the last commit is not about dark / light theme)

**Comment by gmltA** [comment]
Sounds good. But why don't I see these changes in the code?

**Comment by Keckich** [comment]
I'm not sure if I should add .js code in this pr, so you can see changes in my repository for hosting by this link https://github.com/Keckich/front-test/commit/2aab310ce452ae930e97f524266bf0b74612c32f#diff-2ec9bbccd5f5f62459e428180e2fd70b5cecba1f63134e74e423a10c1a4c38dbL8

**Review by gmltA — APPROVED** [review]
To add changes into PR you had to push them into corresponding branch `html+css` in your case.

Okay, that's enough. Here's your <kbd>9</kbd>.

**Comment by gmltA** [comment]
So everything's done?

**Comment by Keckich** [comment]
If we're talking about html and css I think yes. And I wait when you check my js. Also I need to add autodeploy but it will be another pr I think.

**Pull request merged**
